# Generated by Django 3.1.6 on 2021-02-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210216_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CATPartent',
            new_name='CATParent',
        ),
    ]
