# Generated by Django 3.1.6 on 2021-02-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='category_description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImage',
            field=models.ImageField(upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=50, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main_category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCAlternatives',
            field=models.ManyToManyField(related_name='accessories_products', to='product.Product', verbose_name='product_accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product_alternatives',
            name='PALNAlternatives',
            field=models.ManyToManyField(related_name='alternative_products', to='product.Product', verbose_name='product_alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternatives',
            name='PALNProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='product'),
        ),
    ]
