# Generated by Django 3.1.6 on 2021-02-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prdslug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDSlug',
        ),
        migrations.AddField(
            model_name='product',
            name='PRDSLug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product URL'),
        ),
    ]
