# Generated by Django 3.1.6 on 2021-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210221_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount Pric'),
        ),
    ]
